#!/bin/bash

#zrun
#Written by Storm Dragon
#Released under the terms of the WTFPL LIcense: http://wtfpl.net

#This adds an accessible (to screen readers) run dialog wherever it is needed, e.g. ratpoison or fluxbox
#It keeps a history of programs and commands in $0.history, usually zrun.history

#XDG compliance
if [ -z "$XDG_CONFIG_HOME" ] ; then
    XDG_CONFIG_HOME="$HOME/.config"
fi
#Set history file path.
historyPath="$XDG_CONFIG_HOME/$(basename "$0")"
if ! [ -d "$historyPath" ] ; then
    mkdir "$historyPath"
fi

#Update history function
write_history()
{
    #Add latest item if it isn't in the list already.
    if ! grep "$txt" "$historyPath/history" ; then
        oldHistory="$(head -n 49 "$historyPath/history")"
        if [ -n "$oldHistory" ] ; then
            echo -e "$txt\n$oldHistory" > "$historyPath/history"
        else
            echo "$txt" > "$historyPath/history"
        fi
    fi
}

#create command dialog.
if [ -f "$historyPath/history" ] ; then
    txt=$(zenity --list --editable --title "Run Dialog" --text "Execute program or enter file" --ok-label Open --separator "\n" --column "Select from list or enter new" < "$historyPath/history")
else
    txt=$(zenity --entry --title "Run Dialog" --text "Execute program or enter file" --ok-label Open)
fi
#close if canceled.
if [ -z "$txt" ] ; then
    exit 0
fi
#If item is website, open it.
if [[ "$txt" =~ ^www\.[1-zA-Z0-9].*\.[a-zA-Z].* ]] ; then
    txt="http://$txt"
    xdg-open $txt
    write_history
    exit 0
fi
#if item is a program run it, else open file browser, currently hard coded to Caja.
if hash "$(echo "$txt" | cut -d " " -f1)" &> /dev/null ; then
    $txt &
else
    (xdg-open $txt || caja)&
fi
write_history
exit 0
